name: Deploy

on:
  push:
    branches:
      - main
    tags:
      - "!**"

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    services:
      db:
        image: postgres:14.4-alpine
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: typegraphql-prisma
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-${{ matrix.node-version }}
          restore-keys: |
            ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-${{ matrix.node-version }}

      - name: Setup project
        run: |
          npm ci --no-fund --no-audit --no-update-notifier --include=dev --include=optional

      - name: Check codebase
        run: |
          npm run check:format
          npm run check:type

      - name: Run tests
        run: |
          npm run test:ci
        env:
          CI: true
          TEST_DATABASE_URL: postgresql://user:password@localhost:5432/typegraphql-prisma

  publish-preview:
    runs-on: ubuntu-latest
    needs: check

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-22.x
          restore-keys: |
            ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-22.x

      - name: Setup project
        run: |
          npm ci --no-fund --no-audit --no-update-notifier --include=dev --include=optional

      - name: Build
        run: npm run build

      - name: Publish to pkg.pr.new
        run: npx pkg-pr-new publish

  # deploy-website:
  #   if: ${{ github.ref == 'refs/heads/main' }}

  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: "16"

  #     - name: Build Docusaurus website
  #       run: |
  #         cd website
  #         npm i
  #         npm run build

  #     - uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./website/build
  #         user_name: "gh-actions"
  #         user_email: "actions@github.com"
  #         commit_message: |
  #           Deploy website
  #           Deploy website version based on
